"""
IG Earnings Calendar — Logo Downloader
Downloads company logos using bare ticker names that match the calendar widget.
The calendar widget looks up: cdn.jsdelivr.net/.../logos/{TICKER}.png
So logos MUST be saved as {TICKER}.png (no _US, _UK, _DE suffixes).

Run via GitHub Actions (workflow_dispatch) or locally:
    python3 companies.py

Logos are saved to ../logos/ relative to this script's location.
"""

import os
import urllib.request
import time
import sys

# ---------------------------------------------------------------------------
# MASTER TICKER → DOMAIN MAP
# Bare tickers only — must match what the calendar widget uses after stripping
# the Bloomberg exchange suffix and removing dots from UK tickers.
# ---------------------------------------------------------------------------

companies = {

    # ══════════════════════════════════════════════════════════════════════════
    # UK & IRELAND (London-listed) — FTSE 100, FTSE 250, investment trusts
    # Tickers use dot-removed convention: BT.A → BTA, AV. → AV, etc.
    # ══════════════════════════════════════════════════════════════════════════

    # FTSE 100
    "AAF": "airtelafricaplc.com",
    "AAL": "angloamerican.com",
    "ABF": "abf.co.uk",
    "ABDN": "abrdn.com",
    "ADM": "admiralgroup.co.uk",
    "AHT": "ashtead-group.com",
    "ANTO": "antofagasta.co.uk",
    "AV": "aviva.com",
    "AZN": "astrazeneca.com",
    # NOTE: BA. LN (BAE Systems) and BA US (Boeing) both resolve to "BA"
    # Only one BA.png can exist. Calendar should use context to pick correctly.
    # If BAE appears more often in your calendar, swap this to bae.co.uk
    "BA": "boeing.com",
    "BARC": "barclays.co.uk",
    "BATS": "bat.com",
    "BEZ": "beazley.com",
    "BKG": "berkeleygroup.co.uk",
    "BLND": "britishland.com",
    "BME": "bmeuropeanvalueretail.com",
    "BNZL": "bunzl.com",
    "BOY": "bodycotemetal.com",
    "BP": "bp.com",
    "BRBY": "burberry.com",
    "BTA": "bt.com",
    "CNA": "centrica.com",
    "CPG": "compassgroup.com",
    "CRDA": "croda.com",
    "CRH": "crh.com",
    "CTEC": "convatecgroup.com",
    "DCC": "dcc.ie",
    "DGE": "diageo.com",
    "DPLM": "diplomaplc.com",
    "EDV": "endeavourmining.com",
    "ENT": "entaingroup.com",
    "EXPN": "experianplc.com",
    "EZJ": "easyjet.com",
    "FCIT": "foreignandcolonial.com",
    "FRAS": "frasers.group",
    "FRES": "fresnilloplc.com",
    "GLEN": "glencore.com",
    "GSK": "gsk.com",
    "HIK": "hikma.com",
    "HLMA": "halma.com",
    "HL": "hargreaveslansdown.co.uk",
    "HSBA": "hsbc.com",
    "HWDN": "howdengroup.com",
    "IAG": "iairgroup.com",
    "ICG": "icgam.com",
    "IHG": "ihgplc.com",
    "III": "3i.com",
    "IMB": "imbtopline.com",
    "INF": "informa.com",
    "ITRK": "intertek.com",
    "ITV": "itv.com",
    # NOTE: JD. LN (JD Sports) and JD US (JD.com) both resolve to "JD"
    # Keeping JD Sports as it appears more often in UK-focused calendars
    "JD": "jdplc.com",
    "KGF": "kingfisher.com",
    "LAND": "landsecurities.com",
    "LGEN": "legalandgeneralgroup.com",
    "LLOY": "lloydsbankinggroup.com",
    "LSEG": "lseg.com",
    "MKS": "marksandspencer.com",
    "MNG": "mandg.com",
    "MNDI": "mondigroup.com",
    "MRO": "melrose.co.uk",
    "NG": "nationalgrid.com",
    "NWG": "natwestgroup.com",
    "NXT": "nextplc.co.uk",
    "PHNX": "thephoenixgroup.com",
    "PRU": "prudential.co.uk",
    "PSH": "pershingsquareholdings.com",
    "PSN": "persimmonhomes.com",
    "PSON": "pearson.com",
    "REL": "relx.com",
    "RIO": "riotinto.com",
    "RKT": "reckitt.com",
    "RMV": "rightmove.co.uk",
    "RR": "rolls-royce.com",
    "RTO": "rentokil-initial.com",
    "SAG": "smiths.com",
    "SBRY": "about.sainsburys.co.uk",
    "SDR": "schroders.com",
    "SGE": "sage.com",
    "SGRO": "segro.com",
    "SHEL": "shell.com",
    "SKG": "smurfitwestrock.com",
    "SMIN": "smiths.com",
    "SMT": "bfrg.com",
    "SN": "smith-nephew.com",
    "SPX": "spirax-sarco.com",
    "SSE": "sse.com",
    "STAN": "sc.com",
    "STJ": "sjp.co.uk",
    "SVT": "severntrent.com",
    "TATE": "tateandlyle.com",
    "TCIT": "thecitigroup.com",
    "TSCO": "tescoplc.com",
    "TW": "taylorwimpey.co.uk",
    "ULVR": "unilever.com",
    "UU": "unitedutilities.com",
    "VOD": "vodafone.com",
    "WEIR": "global.weir",
    "WPP": "wpp.com",
    "WTB": "whitbread.co.uk",

    # FTSE 250 & other London-listed (commonly appearing in earnings calendars)
    "3IN": "3i-infrastructure.com",
    "AGR": "assuragroup.co.uk",
    "AJB": "ajbell.co.uk",
    "AML": "astonmartinlagonda.com",
    "AO": "ao-world.com",
    "ASC": "asos.com",
    "AUTO": "autotrader.co.uk",
    "ASHM": "ashmorecorp.com",
    "ATST": "alliancetrust.co.uk",
    "BAB": "babcockinternational.com",
    "BDEV": "barrattdevelopments.co.uk",
    "BGEO": "bgeo.com",
    "BIRG": "bankofireland.com",
    "BNKR": "bankerstrust.co.uk",
    "BOKU": "boku.com",
    "BOOT": "boots-uk.com",
    "BOWL": "hollywoodbowlgroup.com",
    "BRSC": "blackrock.com",
    "BYIT": "bytesplc.com",
    "BYG": "bigyellow.co.uk",
    "CCH": "coca-colahbc.com",
    "CCR": "candcgroupplc.com",
    "CEY": "centamin.com",
    "CHG": "chemring.co.uk",
    "CHRY": "chrysalisinvestments.co.uk",
    "CINE": "cineworld.com",
    "CKN": "clarkson.com",
    "CLDN": "caledonia.com",
    "CLN": "cleaninggroup.com",
    "CMCX": "cmcmarkets.com",
    "CRW": "craneware.com",
    "CURY": "currys.co.uk",
    "CWK": "cranswick.co.uk",
    "DARK": "darktrace.com",
    "DSCV": "discoverie.com",
    "DOCS": "drmartens.com",
    "DNLM": "dunelm.com",
    "FGEN": "foresight.group",
    "FGP": "firstgroupplc.com",
    "FSG": "foresightgroup.eu",
    "FUTR": "futureplc.com",
    "GBG": "gbgplc.com",
    "GNC": "greencore.com",
    "GPE": "gpe.co.uk",
    "GRG": "greggs.co.uk",
    "GROW": "moltenventures.com",
    "GYM": "thegymgroup.com",
    "HAS": "hays.com",
    "HBR": "harbourenergy.com",
    "HICL": "hicl.com",
    "HOC": "hochschildmining.com",
    "HSXL": "hiscoxgroup.com",
    "HVPE": "harbourvest.com",
    "HYVE": "hyve.group",
    "IHP": "integrafin.co.uk",
    "INCH": "inchcape.com",
    "INVP": "investec.com",
    "ITH": "ithacaenergy.com",
    "IWG": "iwgplc.com",
    "JEGI": "jpmorgan.com",
    "JET2": "jet2.com",
    "JMAT": "matthey.com",
    "JTC": "jtcgroup.com",
    "JUP": "jupiteram.com",
    "KIE": "kier.co.uk",
    "KNOS": "kainos.com",
    "KWS": "keywordsstudios.com",
    "LMP": "londonmetric.com",
    "LMPL": "liontrust.co.uk",
    "LWDB": "lawdebenture.com",
    "MAB": "mbplc.com",
    "MTO": "mitie.com",
    "MOON": "moonpig.com",
    "N91": "ninetyone.com",
    "NCC": "nccgroup.com",
    "OCDO": "ocadogroup.com",
    "ONT": "nanoporetech.com",
    "OSB": "osbgroup.com",
    "OTB": "onthebeach.co.uk",
    "OXIG": "oxford-instruments.com",
    "PAGE": "pagegroup.com",
    "PAG": "paragonbankinggroup.co.uk",
    "PCGH": "polarcapitaltechnology.co.uk",
    "PETS": "petsathome.com",
    "PFD": "premierfoodsplc.com",
    "PNN": "pennon-group.co.uk",
    "PLUS": "plus500.com",
    "PTEC": "playtech.com",
    "QLT": "quilter.com",
    "QQ": "qinetiq.com",
    "RCH": "reachplc.com",
    "RMG": "royalmail.com",
    "RPI": "raspberrypi.com",
    "RS1": "rsgroup.com",
    "RSW": "renishaw.com",
    "RWA": "robertwalters.com",
    "SAFE": "safestore.co.uk",
    "SCT": "softcat.com",
    "SEIT": "sdcl.com",
    "SEQI": "sequoia-economic.com",
    "SHI": "s4capital.com",
    "SPI": "spirehealthcare.com",
    "SRP": "serco.com",
    "SSPG": "foodtravelexperts.com",
    "SYNC": "syncona.com",
    "TEM": "temit.co.uk",
    "TEP": "telecomplus.co.uk",
    "THGP": "thg.com",
    "TPK": "travisperkins.co.uk",
    "TRY": "trproperty.com",
    "VCT": "victrex.com",
    "VTY": "vistrygroup.co.uk",
    "WISE": "wise.com",
    "WIZZ": "wizzair.com",
    "WKP": "workspace.co.uk",
    "WOSG": "watches-of-switzerland.com",
    "WSE": "thewisegroup.co.uk",
    "XPS": "xpsgroup.com",
    "ZIG": "zigup.com",

    # Ireland-listed (but UK category in calendar)
    "ACN": "accenture.com",
    "RYA": "ryanair.com",
    "PDD": "pinduoduo.com",
    "MDT": "medtronic.com",

    # ══════════════════════════════════════════════════════════════════════════
    # EUROPE — DAX, CAC 40, SMI, STOXX 50, OMX 30, Nordic, Benelux, Southern
    # ══════════════════════════════════════════════════════════════════════════

    # Germany — DAX 40 + MDAX
    "ADS": "adidas.com",
    "AIR": "airbus.com",
    "ALV": "allianz.com",
    "BAS": "basf.com",
    "BAYN": "bayer.com",
    "BEI": "beiersdorf.com",
    "BMW": "bmw.com",
    "BNR": "brenntag.com",
    "CBK": "commerzbank.com",
    "CON": "continental.com",
    "DB1": "deutsche-boerse.com",
    "DBK": "db.com",
    "DHL": "dhl.com",
    "DTE": "telekom.com",
    "DTG": "daimler-truck.com",
    "EOAN": "eon.com",
    "EVD": "eventim.de",
    "EVK": "evonik.com",
    "FME": "freseniusmedicalcare.com",
    "FRE": "fresenius.com",
    "FNTN": "freenet.de",
    "HAG": "hensoldt.net",
    "HEI": "heidelbergmaterials.com",
    "HEN3": "henkel.com",
    "HFG": "hellofresh.com",
    "HLE": "hella.com",
    "IFX": "infineon.com",
    "KGX": "kiongroup.com",
    "LEG": "leg-wohnen.de",
    "LHA": "lufthansa.com",
    "MBG": "mercedes-benz.com",
    "MRK": "merckgroup.com",
    "MTU": "mtu.de",
    "MUV2": "munichre.com",
    "NEM": "nemetschek.com",
    "P911": "porsche.com",
    "PAH3": "porsche-se.com",
    "PUM": "puma.com",
    "RHM": "rheinmetall.com",
    "RWE": "rwe.com",
    "SAP": "sap.com",
    "SHL": "siemens-healthineers.com",
    "SIE": "siemens.com",
    "SRE": "siriusrealestate.com",
    "SY1": "symrise.com",
    "TKA": "thyssenkrupp.com",
    "TUI": "tui.com",
    "VNA": "vonovia.de",
    "VOW3": "volkswagen.com",
    "ZAL": "zalando.de",

    # France — CAC 40 + SBF 120
    "ACA": "credit-agricole.com",
    "ATO": "atos.net",
    "BN": "danone.com",
    "BNP": "bnpparibas.com",
    "CAP": "capgemini.com",
    # NOTE: DG FP (Vinci) and DG US (Dollar General) both resolve to "DG"
    # Keeping Vinci as primary since it's in the French CAC 40 section
    "DG": "vinci.com",
    "DSY": "3ds.com",
    "ENGI": "engie.com",
    "FGR": "eiffage.com",
    "HO": "thalesgroup.com",
    "KER": "kering.com",
    "LR": "legrand.com",
    "MC": "lvmh.com",
    "ML": "michelin.com",
    "OR": "loreal.com",
    "ORA": "orange.com",
    "PUB": "publicisgroupe.com",
    "RI": "pernod-ricard.com",
    "RMS": "hermes.com",
    "RNO": "renaultgroup.com",
    "SAF": "safran-group.com",
    "SAN": "santander.com",
    "SGO": "saint-gobain.com",
    "SU": "schneider-electric.com",
    "TTE": "totalenergies.com",
    "URW": "urw.com",
    "VIE": "veolia.com",
    "VIV": "vivendi.com",
    "AMP": "amplifon.com",
    "ABVX": "abivax.com",

    # Switzerland — SMI + SPI
    "CFR": "richemont.com",
    "SOON": "sonova.com",
    "NESN": "nestle.com",
    "NOVN": "novartis.com",
    "ROG": "roche.com",
    "UBSG": "ubs.com",
    "SREN": "swissre.com",
    "ZURN": "zurich.com",
    "GIVN": "givaudan.com",
    "SIK": "sika.com",
    "GEBN": "geberit.com",
    "PGHN": "partnersgroup.com",
    "BAER": "juliusbaer.com",
    "LOGN": "logitech.com",
    "LONN": "lonza.com",
    "SCMN": "swisscom.com",
    "HOLN": "holcim.com",
    "TEMN": "temenos.com",
    "KNIN": "kuehne-nagel.com",
    "STMN": "straumann.com",
    "SLHN": "swisslife.com",
    "BARN": "barrygroup.com",
    "EMSN": "ems-group.com",

    # Netherlands
    "AD": "ahold.com",
    "ADYEN": "adyen.com",
    "AKZA": "akzonobel.com",
    "ASML": "asml.com",
    "ASM": "asm.com",
    "ENX": "euronext.com",
    "INGA": "ing.com",
    "NN": "nn-group.com",
    "PHIA": "philips.com",
    "PRX": "prosus.com",
    "RAND": "randstad.com",
    "UNA": "unilever.com",
    "WKL": "wolterskluwer.com",
    "IMCD": "imcdgroup.com",
    "CSG": "csg.nl",

    # Belgium
    "ABI": "ab-inbev.com",
    "AED": "aedifica.eu",
    "AGS": "ageas.com",
    "COLR": "colruytgroup.com",
    "KBC": "kbc.com",
    "SOLB": "solvay.com",
    "UCB": "ucb.com",
    "SYENS": "syensqo.com",

    # Nordics — Sweden
    "ADDTB": "addtech.com",
    "ALFAB": "alfa.com",
    "ASSA": "assaabloy.com",
    "ATCOA": "atlascopco.com",
    "AZA": "avanza.se",
    "BALDB": "balder.se",
    "BOL": "boliden.com",
    "ERICB": "ericsson.com",
    "EVO": "evolution.com",
    "HEXA": "hexagon.com",
    "HMB": "hm.com",
    "HUSQ": "husqvarna.com",
    "INDUA": "industrivarden.se",
    "INVE": "investorab.com",
    "KINV": "kinnevik.com",
    "LAGRB": "lagercrantz.com",
    "LATOB": "latour.se",
    "LIFCOB": "lifco.se",
    "LUNDB": "lundbergforetagen.se",
    "MYCR": "mycronic.com",
    "NIBEB": "nibe.se",
    "SAGAA": "sagax.se",
    "SAND": "sandvik.com",
    "SCA": "sca.com",
    "SECU": "securitas.com",
    "SECTB": "sectra.com",
    "SKF": "skf.com",
    "SSAB": "ssab.com",
    "SEB": "sebgroup.com",
    "SWED": "swedbank.com",
    "TELIA": "teliacompany.com",
    "TREL": "trelleborg.com",
    "VOLV": "volvo.com",
    "WALLB": "wallenstam.se",
    "WIHL": "wihlborgs.se",
    "ESSITY": "essity.com",
    "NDA": "nordea.com",
    "SINCH": "sinch.com",

    # Denmark
    "CARL": "carlsberggroup.com",
    "COLO": "coloplast.com",
    "DSV": "dsv.com",
    "GMAB": "genmab.com",
    "ISS": "issworld.com",
    "MAERSK": "maersk.com",
    "NOVO": "novonordisk.com",
    "NZYM": "novozymes.com",
    "ORSTED": "orsted.com",
    "PNDORA": "pandoragroup.com",
    "ROCKB": "rockwool.com",
    "TRYG": "tryg.com",
    "VWS": "vestas.com",
    "AMBU": "ambu.com",
    "GN": "gn.com",
    "DEMANT": "demant.com",

    # Norway
    "AKRBP": "akerbp.com",
    "BAKKA": "bakkafrost.com",
    "DNB": "dnb.no",
    "EQNR": "equinor.com",
    "FRO": "frontlinetankers.com",
    "GJF": "gjensidige.com",
    "KOG": "kongsberg.com",
    "KMAR": "km.kongsberg.com",
    "MOWI": "mowi.com",
    "NHY": "hydro.com",
    "ORK": "orkla.com",
    "SALM": "salmar.no",
    "SUBC": "subsea7.com",
    "TEL": "telenor.com",
    "TOM": "tomra.com",
    "YAR": "yara.com",
    "SCHB": "schibsted.com",

    # Finland
    "ELISA": "elisa.com",
    "FORTUM": "fortum.com",
    "KEMIRA": "kemira.com",
    "KNEBV": "kone.com",
    "NESTE": "neste.com",
    "NOKIA": "nokia.com",
    "SAMPO": "sampo.com",
    "STERV": "storaenso.com",
    "UPM": "upm.com",
    "WRTBV": "wartsila.com",

    # Italy
    "AMP_IT": "amplifon.com",
    "BAMI": "bancobpm.it",
    "ENEL": "enel.com",
    "ENI": "eni.com",
    "G": "generali.com",
    "IP": "interpumpgroup.it",
    "ISP": "intesasanpaolo.com",
    "MB": "mediobanca.it",
    "MONC": "moncler.com",
    "PRY": "prysmian.com",
    "RACE": "ferrari.com",
    "REC": "recordati.com",
    "REY": "reply.com",
    "STM": "st.com",
    "TIT": "telecomitalia.com",
    "TRN": "terna.it",
    "UCG": "unicreditgroup.eu",
    "UNI": "unipol.it",

    # Spain
    "AENA": "aena.es",
    "BBVA": "bbva.com",
    "CABK": "caixabank.com",
    "CLNX": "cellnex.com",
    "ELE": "endesa.com",
    "ENG": "enagas.es",
    "FER": "ferrovial.com",
    "GRF": "grifols.com",
    "IBE": "iberdrola.com",
    "ITX": "inditex.com",
    "MAP": "mapfre.com",
    "REP": "repsol.com",
    "SAB": "grupobancosabadell.com",
    "TEF": "telefonica.com",
    "ATYM": "atalyamining.com",

    # Portugal
    "BCP": "millenniumbcp.pt",
    "GALP": "galp.com",
    "JMT": "jeronimomartins.com",

    # Austria
    "EBS": "erstegroup.com",
    "OMV": "omv.com",
    "RBI": "rbinternational.com",
    "VOE": "voestalpine.com",
    "WIE": "wienerberger.com",
    "VIG": "vig.com",

    # Poland
    "ACP": "assecopoland.com",
    "ALE": "allegro.eu",
    "CDR": "cdprojektred.com",
    "KGH": "kghm.com",
    "LPP": "lppsa.com",
    "OPL": "orange.pl",
    "PEO": "pekao.com.pl",
    "PKN": "orlen.pl",
    "PKO": "pkobp.pl",
    "PZU": "pzu.pl",
    "TPE": "tauronpe.pl",

    # Czech / Hungary / Faroe Islands / Lithuania
    "CEZ": "cez.cz",
    "KOMB": "kb.cz",
    "MOL": "mol.hu",
    "OTP": "otpbank.hu",
    "BCG": "balticclassifieds.com",

    # ══════════════════════════════════════════════════════════════════════════
    # UNITED STATES & CANADA — S&P 500, Nasdaq 100, popular mid-caps
    # ══════════════════════════════════════════════════════════════════════════

    # Mega-cap tech
    "AAPL": "apple.com",
    "MSFT": "microsoft.com",
    "GOOGL": "google.com",
    "AMZN": "amazon.com",
    "META": "meta.com",
    "NVDA": "nvidia.com",
    "TSLA": "tesla.com",
    "AVGO": "broadcom.com",
    "ORCL": "oracle.com",
    "CRM": "salesforce.com",
    "ADBE": "adobe.com",
    "AMD": "amd.com",
    "INTC": "intel.com",
    "CSCO": "cisco.com",
    "IBM": "ibm.com",
    "NOW": "servicenow.com",
    "INTU": "intuit.com",
    "AMAT": "appliedmaterials.com",
    "ADI": "analog.com",
    "LRCX": "lamresearch.com",
    "KLAC": "kla.com",
    "MRVL": "marvell.com",
    "SNPS": "synopsys.com",
    "CDNS": "cadence.com",
    "PANW": "paloaltonetworks.com",
    "CRWD": "crowdstrike.com",
    "WDAY": "workday.com",
    "ADSK": "autodesk.com",
    "NXPI": "nxp.com",
    "MU": "micron.com",
    "MSTR": "microstrategy.com",
    "ARM": "arm.com",
    "PLTR": "palantir.com",
    "APP": "applovin.com",

    # Financials
    "JPM": "jpmorganchase.com",
    "BAC": "bankofamerica.com",
    "WFC": "wellsfargo.com",
    "GS": "goldmansachs.com",
    "MS": "morganstanley.com",
    "C": "citigroup.com",
    "BX": "blackstone.com",
    "BLK": "blackrock.com",
    "SCHW": "aboutschwab.com",
    "AXP": "americanexpress.com",
    "V": "visa.com",
    "MA": "mastercard.com",
    "PYPL": "paypal.com",
    "COF": "capitalone.com",
    "SQ": "squareup.com",
    "COIN": "coinbase.com",
    "HOOD": "robinhood.com",
    "SOFI": "sofi.com",
    "AFRM": "affirm.com",
    "KLAR": "klarna.com",

    # Retail & consumer
    "WMT": "walmart.com",
    "COST": "costco.com",
    "HD": "homedepot.com",
    "LOW": "lowes.com",
    "TGT": "target.com",
    "TJX": "tjx.com",
    "ROST": "rossstores.com",
    # DG already defined above (Vinci FP/Dollar General US conflict — see note)
    "DLTR": "dollartree.com",
    "BBY": "bestbuy.com",
    "KR": "thekrogerco.com",
    "NKE": "nike.com",
    "LULU": "lululemon.com",
    "RL": "ralphlauren.com",
    "DECK": "deckers.com",
    "BIRK": "birkenstock.com",
    "ONON": "on-running.com",
    "WSM": "williams-sonoma.com",
    "ULTA": "ultabeauty.com",
    "HIMS": "forhims.com",
    "FIVE": "fivebelow.com",
    "CAVA": "cava.com",
    "CPRT": "copart.com",

    # Healthcare
    "UNH": "unitedhealthgroup.com",
    "JNJ": "jnj.com",
    "LLY": "lilly.com",
    "PFE": "pfizer.com",
    "ABBV": "abbvie.com",
    "BMY": "bms.com",
    "AMGN": "amgen.com",
    "GILD": "gilead.com",
    "MRNA": "modernatx.com",
    "REGN": "regeneron.com",
    "VRTX": "vrtx.com",
    "ISRG": "intuitive.com",
    "TMO": "thermofisher.com",
    "DHR": "danaher.com",
    "ABT": "abbott.com",
    "BNTX": "biontech.com",
    "DXCM": "dexcom.com",
    "VEEV": "veeva.com",
    "IDXX": "idexx.com",
    "COO": "coopercos.com",

    # Industrials
    "DE": "deere.com",
    "CAT": "caterpillar.com",
    "HON": "honeywell.com",
    "GE": "ge.com",
    "RTX": "rtx.com",
    "LMT": "lockheedmartin.com",
    # BA already defined above (UK/US conflict — see note)
    "GD": "gd.com",
    "NOC": "northropgrumman.com",
    "LHX": "l3harris.com",
    "FDX": "fedex.com",
    "UPS": "ups.com",
    "UNP": "unionpacific.com",
    "CSX": "csx.com",
    "NSC": "nscorp.com",
    "EMR": "emerson.com",
    "ETN": "eaton.com",
    "WM": "wm.com",
    "RSG": "republicservices.com",
    "FAST": "fastenal.com",
    "URI": "unitedrentals.com",
    "CTAS": "cintas.com",
    "KEYS": "keysight.com",
    "NDSN": "nordson.com",
    "SUNB": "sunbeltrentals.com",

    # Energy
    "XOM": "exxonmobil.com",
    "CVX": "chevron.com",
    "COP": "conocophillips.com",
    "SLB": "slb.com",
    "EOG": "eogresources.com",
    "OXY": "oxy.com",
    "PSX": "phillips66.com",
    "MPC": "marathonpetroleum.com",
    "VLO": "valero.com",
    "HAL": "halliburton.com",
    "CEG": "constellationenergy.com",
    "PLUG": "plugpower.com",
    "OKLO": "oklo.com",

    # Media & entertainment
    "DIS": "thewaltdisneycompany.com",
    "NFLX": "netflix.com",
    "CMCSA": "comcast.com",
    "TTWO": "take2games.com",
    "EA": "ea.com",
    "RBLX": "roblox.com",
    "SPOT": "spotify.com",
    "ROKU": "roku.com",
    "WBD": "wbd.com",
    "FOX": "foxcorporation.com",
    "FOXA": "foxcorporation.com",
    "LYV": "livenationentertainment.com",
    "PARA": "paramount.com",
    "GME": "gamestop.com",

    # Telecom & comm services
    "T": "att.com",
    "VZ": "verizon.com",
    "TMUS": "t-mobile.com",

    # Consumer staples
    "PG": "pg.com",
    "KO": "coca-colacompany.com",
    "PEP": "pepsico.com",
    "PM": "pmi.com",
    "MO": "altria.com",
    "CL": "colgate.com",
    "KMB": "kimberly-clark.com",
    "GIS": "generalmills.com",
    "KHC": "kraftheinz.com",
    "SJM": "jmsmucker.com",
    "CAG": "conagra.com",
    "HRL": "hormelfoodscorporation.com",
    "CPB": "campbells.com",
    "MKC": "mccormick.com",
    "HSY": "thehersheycompany.com",
    "MDLZ": "mondelezinternational.com",
    "KDP": "keurigdrpepper.com",
    "STZ": "cbrands.com",
    "TAP": "molsoncoors.com",
    "BFB": "brown-forman.com",
    "SYY": "sysco.com",

    # REITs & real estate
    "AMT": "americantower.com",
    "PLD": "prologis.com",
    "CCI": "crowncastle.com",
    "EQIX": "equinix.com",
    "SPG": "simon.com",
    "DLR": "digitalrealty.com",
    "O": "realtyincome.com",
    "WELL": "welltower.com",
    "PSA": "publicstorage.com",
    "IRM": "ironmountain.com",
    "VTR": "ventasreit.com",
    "EQR": "equityapartments.com",

    # Software & SaaS
    "SNOW": "snowflake.com",
    "DDOG": "datadoghq.com",
    "ZS": "zscaler.com",
    "NET": "cloudflare.com",
    "MDB": "mongodb.com",
    "TEAM": "atlassian.com",
    "HUBS": "hubspot.com",
    # VEEV already defined in Healthcare section
    "MNDY": "monday.com",
    "BILL": "bill.com",
    "GTLB": "gitlab.com",
    "PATH": "uipath.com",
    "ESTC": "elastic.co",
    "OKTA": "okta.com",
    "TWLO": "twilio.com",
    "DOCU": "docusign.com",
    "ZM": "zoom.us",
    "FROG": "jfrog.com",
    "BRZE": "braze.com",

    # Autos & transport
    "DAL": "delta.com",
    "UAL": "ual.com",
    "LUV": "southwest.com",
    "AAL_US": "aa.com",
    "CCL": "carnival.com",
    "NCLH": "ncl.com",
    "RCL": "royalcaribbean.com",
    "UBER": "uber.com",
    "LYFT": "lyft.com",
    "RIVN": "rivian.com",
    "GM": "gm.com",
    "F": "ford.com",

    # Food & restaurants
    "MCD": "mcdonalds.com",
    "SBUX": "starbucks.com",
    "CMG": "chipotle.com",
    "YUM": "yum.com",
    "DPZ": "dominos.com",
    "DRI": "dfrg.com",
    "WING": "wingstop.com",
    "SHAK": "shakeshack.com",

    # Semiconductors & hardware
    "QCOM": "qualcomm.com",
    "TXN": "ti.com",
    "ON": "onsemi.com",
    "MCHP": "microchip.com",
    "SWKS": "skyworks.com",
    "SMCI": "supermicro.com",
    "DELL": "dell.com",
    "HPE": "hpe.com",
    "HPQ": "hp.com",
    "NTAP": "netapp.com",
    "STX": "seagate.com",
    "WDC": "westerndigital.com",

    # Internet & e-commerce
    "BABA": "alibaba.com",
    # JD.com (JD US) conflicts with JD Sports (JD. LN) — see UK section
    "SE": "sea.com",
    "SHOP": "shopify.com",
    "ETSY": "etsy.com",
    "EBAY": "ebay.com",
    "CHWY": "chewy.com",
    "W": "wayfair.com",
    "MELI": "mercadolibre.com",
    "CPNG": "coupang.com",
    "GRAB": "grab.com",
    "NU": "nu.com.br",

    # Insurance & diversified financial
    "BRK": "berkshirehathaway.com",
    "PGR": "progressive.com",
    "TRV": "travelers.com",
    "ALL": "allstate.com",
    "MET": "metlife.com",
    "AFL": "aflac.com",
    "AIG": "aig.com",
    "HIG": "thehartford.com",
    "CB": "chubb.com",
    "MMC": "mmc.com",
    "AON": "aon.com",
    "WTW": "wtwco.com",
    "ARES": "aresmgmt.com",
    "KKR": "kkr.com",
    "APO": "apollo.com",

    # Utilities
    "NEE": "nexteraenergy.com",
    "DUK": "duke-energy.com",
    "SO": "southerncompany.com",
    "D": "dominionenergy.com",
    "AEP": "aep.com",
    # SRE already defined above (Sirius Real Estate GR). Sempra is also SRE US.
    "EXC": "exelon.com",
    "XEL": "xcelenergy.com",
    "ED": "coned.com",
    "WEC": "wecenergygroup.com",
    "ES": "eversource.com",

    # Biotech
    "BIIB": "biogen.com",
    "ALNY": "alnylam.com",
    "BMRN": "biomarin.com",
    "NBIX": "neurocrine.com",
    "SRPT": "sarepta.com",
    "ARGX": "argenx.com",
    "BGNE": "beigene.com",
    "IONS": "ionispharma.com",

    # Crypto & fintech
    "MARA": "mara.com",
    "RIOT": "riotplatforms.com",
    "CLSK": "cleanspark.com",
    "HUT": "hut8.com",
    "BITF": "bitfarms.com",
    "CIFR": "cipher.com",
    "IREN": "iris-energy.com",
    "BTDR": "bitdeer.com",
    "CORZ": "core-scientific.com",

    # Space & defense
    "ASTS": "ast-science.com",
    "RKLB": "rocketlabusa.com",
    "LUNR": "intuitivemachines.com",
    "AXON": "axon.com",

    # AI & emerging tech
    "IONQ": "ionq.com",
    "RGTI": "rigetti.com",
    "SOUN": "soundhound.ai",
    "AI": "c3.ai",
    "BBAI": "bigbearai.com",
    "NBIS": "nebius.com",

    # Cannabis, EV, SPACs, popular retail
    "LCID": "lucidmotors.com",
    "XPEV": "xpeng.com",
    "NIO": "nio.com",
    "LI": "lixiang.com",
    "BYND": "beyondmeat.com",

    # Other notable US
    "FDS": "factset.com",
    "CIEN": "ciena.com",
    "LEN": "lennar.com",
    "AZO": "autozone.com",
    "ORLY": "oreillyauto.com",
    "PAYX": "paychex.com",
    "FIS": "fisglobal.com",
    "FISV": "fiserv.com",
    "GPN": "globalpayments.com",
    "FI": "fiserv.com",
    "BR": "broadridge.com",
    "JKHY": "jackhenry.com",
    "TYL": "tylertech.com",
    "TTEC": "ttec.com",
    "VIK": "vikingholdings.com",
    "CASY": "caseys.com",

    # Canada
    "TD": "td.com",
    "RY": "rbc.com",
    "BN_CA": "brookfield.com",
    "BMO": "bmo.com",
    "BNS": "scotiabank.com",
    "ATD": "couche-tard.com",
    "SHOP_CA": "shopify.com",

    # Additional Bloomberg file tickers
    "A": "agilent.com",
    "AGT": "aviglobaltrust.com",
    "JBL": "jabil.com",
    "PEY": "partnersgroupprivateequity.com",
    "PPET": "patriagroup.com",
    "UKW": "greencoat-capital.com",

    # IG brand logo
    "IGG": "ig.com",
}


# ---------------------------------------------------------------------------
# DOWNLOAD LOGIC
# ---------------------------------------------------------------------------

LOGO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "logos")
CLEARBIT_URL = "https://logo.clearbit.com/{domain}?size=200"
GOOGLE_URL = "https://www.google.com/s2/favicons?domain={domain}&sz=128"


def download_logo(ticker, domain):
    """Download logo for a ticker. Try Clearbit first, then Google favicons."""
    path = os.path.join(LOGO_DIR, f"{ticker}.png")
    if os.path.exists(path):
        return True

    for url_template in [CLEARBIT_URL, GOOGLE_URL]:
        url = url_template.format(domain=domain)
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = resp.read()
                if len(data) > 500:  # Skip tiny/broken images
                    with open(path, "wb") as f:
                        f.write(data)
                    return True
        except Exception:
            pass
        time.sleep(0.2)

    return False


def main():
    os.makedirs(LOGO_DIR, exist_ok=True)
    total = len(companies)
    ok = 0
    fail = []

    for i, (ticker, domain) in enumerate(sorted(companies.items()), 1):
        success = download_logo(ticker, domain)
        status = "OK" if success else "FAIL"
        if success:
            ok += 1
        else:
            fail.append(ticker)
        print(f"[{i}/{total}] {ticker:<12} {domain:<45} {status}")

    print(f"\nDone: {ok}/{total} logos downloaded")
    if fail:
        print(f"Failed ({len(fail)}): {', '.join(fail)}")


if __name__ == "__main__":
    main()
